# Generated by Django 5.2.11 on 2026-02-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_plan_default_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, help_text='Monthly price (in USD or configured currency)', max_digits=10),
        ),
    ]
