# Generated by Django 5.2.10 on 2026-01-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='facebook_profile',
            field=models.URLField(blank=True, help_text='Facebook profile URL', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='instagram_profile',
            field=models.URLField(blank=True, help_text='Instagram profile URL', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True, help_text='Personal/company website', null=True),
        ),
    ]
