# Generated by Django 5.2.10 on 2026-01-23 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead_facebook_profile_lead_instagram_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='facebook_profile',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='instagram_profile',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='website',
        ),
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('website', 'Website'), ('other', 'Other')], default='other', max_length=20)),
                ('custom_platform', models.CharField(blank=True, help_text="Specify platform name if 'Other' selected", max_length=100, null=True)),
                ('url', models.URLField(help_text='Profile URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_links', to='core.lead')),
            ],
            options={
                'ordering': ['platform'],
            },
        ),
    ]
