# Generated by Django 5.2.10 on 2026-01-26 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='assignment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated budget of the lead', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='conversion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_to_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Additional custom fields as key-value pairs'),
        ),
        migrations.AddField(
            model_name='lead',
            name='decision_maker',
            field=models.BooleanField(default=False, help_text='Is the contact the decision maker?'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_score',
            field=models.IntegerField(default=0, help_text='Score based on lead quality criteria'),
        ),
        migrations.AddField(
            model_name='lead',
            name='timeline',
            field=models.DateField(blank=True, help_text='Expected timeline for decision', null=True),
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('note', 'Note'), ('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('conversion', 'Conversion'), ('assignment', 'Assignment'), ('status_update', 'Status Update')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Activity',
                'verbose_name_plural': 'Lead Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for assignment')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_received', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='core.lead')),
                ('previous_assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Assignment History',
                'verbose_name_plural': 'Lead Assignment Histories',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the custom field', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('choice', 'Choice'), ('textarea', 'Text Area')], default='text', help_text='Type of the field', max_length=20)),
                ('choices', models.TextField(blank=True, help_text='Available choices for choice fields (comma separated)')),
                ('required', models.BooleanField(default=False, help_text='Is this field required?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='LeadSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('permissions', models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit'), ('full', 'Full Access')], default='view', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When sharing access expires', null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='core.lead')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_created', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shared_at'],
                'unique_together': {('lead', 'shared_with')},
            },
        ),
    ]
