# Generated by Django 5.2.10 on 2026-01-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lead_assigned_to_lead_assignment_date_lead_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='scope',
            field=models.CharField(choices=[('all', 'Apply to all leads (bulk)'), ('each', 'Per individual lead')], default='all', help_text='Whether this field applies to all leads or per individual lead', max_length=10),
        ),
    ]
