# Generated by Django 5.2.11 on 2026-02-10 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_activitylog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('lead_added', 'Lead Added'), ('lead_updated', 'Lead Updated'), ('lead_deleted', 'Lead Deleted'), ('lead_assigned', 'Lead Assigned'), ('lead_shared', 'Lead Shared'), ('lead_converted', 'Lead Converted'), ('lead_imported', 'Leads Imported'), ('staff_approved', 'Staff Approved'), ('staff_rejected', 'Staff Rejected'), ('staff_removed', 'Staff Removed'), ('owner_approved', 'Owner Approved'), ('role_assigned', 'Role Assigned'), ('role_created', 'Role Created'), ('plan_upgraded', 'Plan Upgraded'), ('payment_received', 'Payment Received'), ('followup_due', 'Follow-up Due'), ('followup_overdue', 'Follow-up Overdue'), ('template_created', 'Template Created'), ('custom_field_created', 'Custom Field Created'), ('system', 'System')], db_index=True, default='system', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('url', models.CharField(blank=True, help_text='URL to redirect when notification is clicked', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='core_notifi_recipie_1d5476_idx')],
            },
        ),
    ]
