# Generated by Django 5.2.10 on 2026-02-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_lead_contact_number_alter_lead_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this field is active and visible on forms'),
        ),
    ]
