# Generated by Django 5.2.9 on 2026-03-15 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customfield_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_direct_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_direct_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient', '-created_at'], name='core_direct_sender__9b7836_idx'), models.Index(fields=['recipient', 'read_at', '-created_at'], name='core_direct_recipie_b44648_idx'), models.Index(fields=['-created_at'], name='core_direct_created_b8a337_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sender', models.F('recipient')), _negated=True), name='dm_sender_not_recipient')],
            },
        ),
    ]
