# Generated by Django 5.2.9 on 2026-03-15 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_directmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTypingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_typing', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_typing_statuses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['peer', 'is_typing', '-updated_at'], name='core_chatty_peer_id_afeec5_idx'), models.Index(fields=['user', 'peer'], name='core_chatty_user_id_ddcd1f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user', models.F('peer')), _negated=True), name='typing_user_not_peer')],
                'unique_together': {('user', 'peer')},
            },
        ),
    ]
