# Generated by Django 5.2.9 on 2026-04-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_restore_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('no_response', 'No Response'), ('int_not_contacted', 'Interested, Not Contacted'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadtemplate',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('no_response', 'No Response'), ('int_not_contacted', 'Interested, Not Contacted'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
