# Generated by Django 5.2.11 on 2026-02-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_monthly_yearly_leads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['monthly_price']},
        ),
        migrations.AddField(
            model_name='plan',
            name='is_default_signup_plan',
            field=models.BooleanField(default=False, help_text='Auto-assign this plan to new business owners on signup (only 1 allowed)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='monthly_max_leads',
            field=models.IntegerField(blank=True, help_text='Max leads for monthly plan (null = unlimited)', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, help_text='Monthly price in PKR', max_digits=10),
        ),
    ]
