# Generated by Django 5.2.9 on 2026-02-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_plan_monthly_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_employee', models.DecimalField(decimal_places=2, default=2.0, help_text='Price per employee per month (USD)', max_digits=10)),
                ('price_per_lead_block', models.DecimalField(decimal_places=2, default=1.0, help_text='Price per lead block per month (USD)', max_digits=10)),
                ('lead_block_size', models.IntegerField(default=100, help_text='Number of leads per block (e.g., 100 means every 100 leads costs price_per_lead_block)')),
                ('min_employees', models.IntegerField(default=1, help_text='Minimum employees selectable')),
                ('max_employees', models.IntegerField(default=50, help_text='Maximum employees selectable')),
                ('min_leads', models.IntegerField(default=100, help_text='Minimum leads selectable')),
                ('max_leads', models.IntegerField(default=10000, help_text='Maximum leads selectable')),
                ('lead_step', models.IntegerField(default=100, help_text='Leads selection step (e.g., 100, 200, 300...)')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Base monthly price before adding per-employee/per-lead costs', max_digits=10)),
                ('yearly_discount', models.DecimalField(decimal_places=2, default=20.0, help_text='Yearly discount percentage for custom plans', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Enable custom plan builder for business owners')),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configuration',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='custom_max_employees',
            field=models.IntegerField(blank=True, help_text='Custom employee limit (for custom plans)', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='custom_max_leads',
            field=models.IntegerField(blank=True, help_text='Custom lead limit (for custom plans)', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='custom_monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom monthly price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_custom_plan',
            field=models.BooleanField(default=False, help_text='True if this is a custom-configured plan'),
        ),
    ]
