# Generated by Django 5.2.9 on 2026-02-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_pricingconfig_subscription_custom_max_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='employee_step',
            field=models.IntegerField(default=1, help_text='Employee selection step'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='unlimited_employees_price',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Fixed monthly price for unlimited employees', max_digits=10),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='unlimited_leads_price',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Fixed monthly price for unlimited leads', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='lead_block_size',
            field=models.IntegerField(default=1000, help_text='Number of leads per block (e.g., 1000 means every 1000 leads costs price_per_lead_block)'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='lead_step',
            field=models.IntegerField(default=1000, help_text='Leads selection step (e.g., 1000, 2000, 3000...)'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='max_employees',
            field=models.IntegerField(default=500, help_text='Maximum employees selectable'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='max_leads',
            field=models.IntegerField(default=1000000, help_text='Maximum leads selectable (e.g., 1000000 = 10 lakh)'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='min_leads',
            field=models.IntegerField(default=1000, help_text='Minimum leads selectable'),
        ),
    ]
