# Generated by Django 5.2.9 on 2026-02-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_pricingconfig_employee_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(choices=[('pkr', 'PKR - Pakistani Rupee (Rs.)'), ('usd', 'USD - US Dollar ($)'), ('eur', 'EUR - Euro (€)'), ('gbp', 'GBP - British Pound (£)'), ('inr', 'INR - Indian Rupee (₹)'), ('aed', 'AED - UAE Dirham (د.إ)'), ('sar', 'SAR - Saudi Riyal (﷼)'), ('cad', 'CAD - Canadian Dollar (C$)'), ('aud', 'AUD - Australian Dollar (A$)'), ('try', 'TRY - Turkish Lira (₺)')], default='pkr', help_text='Currency used across the platform (plans, payments, Stripe)', max_length=5)),
                ('site_name', models.CharField(default='LeadSync', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, help_text='Monthly price in the configured currency', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='price_per_employee',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Price per employee per month', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='price_per_lead_block',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Price per lead block per month', max_digits=10),
        ),
    ]
