# Generated by Django 5.2.9 on 2026-03-18 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_payment_discount_amount_payment_discount_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='contact_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payments/proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
