# Generated by Django 5.2.9 on 2026-03-19 20:21

import billing.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_backfill_payment_proof_access_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, storage=billing.storage.get_payment_proof_storage, upload_to=''),
        ),
    ]
