# Generated by Django 5.2.9 on 2026-03-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_payment_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_proof_access_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
