# Generated by Django 5.2.9 on 2026-04-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_payment_payment_proof_access_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Account Holder Name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='account_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='easypaisa_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='EasyPaisa Number'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='iban',
            field=models.CharField(blank=True, max_length=50, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='jazzcash_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='JazzCash Number'),
        ),
    ]
