# Generated by Django 5.2.10 on 2026-01-23 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_boss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('boss', 'staff')},
            },
        ),
    ]
