"""
Django settings for LeadSync project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-(%%dakk48pv@19a*1501krq=_m_71tpggda4z2@o!4m*ps)^fa'
)

# SECURITY WARNING: don't run with debug turned on in production!
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)
# DEBUG = True

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='').split(',') if config('CSRF_TRUSTED_ORIGINS', default='') else []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'corsheaders',
    'accounts',
    'core',
    'billing',
    'team',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'billing.middleware.PlanExpiryMiddleware',
]

ROOT_URLCONF = 'LeadSync.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'core.context_processors.stripe_context',
                'core.context_processors.user_permissions_context',
                'core.context_processors.notifications_context',
                'core.context_processors.chat_unread_context',
                'core.context_processors.currency_context',
                'core.context_processors.plan_alert_context',
                'core.context_processors.google_analytics_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'LeadSync.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'leadsync',
        'USER': 'postgres',
        'PASSWORD': 'jiya',
        # 'PASSWORD': '1122',
        # 'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Payment proof storage is locked to local filesystem.
# This keeps uploaded proof images inside the project media folder.
PAYMENT_PROOF_STORAGE_BACKEND = 'filesystem'
PAYMENT_PROOF_ROOT = MEDIA_ROOT / 'payments' / 'proofs'
PAYMENT_PROOF_BASE_URL = f"{MEDIA_URL.rstrip('/')}/payments/proofs/"
if not PAYMENT_PROOF_BASE_URL.startswith('/'):
    PAYMENT_PROOF_BASE_URL = f'/{PAYMENT_PROOF_BASE_URL}'
if not PAYMENT_PROOF_BASE_URL.endswith('/'):
    PAYMENT_PROOF_BASE_URL = f'{PAYMENT_PROOF_BASE_URL}/'

# Google Drive storage settings (used when PAYMENT_PROOF_STORAGE_BACKEND='gdrive')
GOOGLE_DRIVE_OAUTH_CLIENT_ID = config('GOOGLE_DRIVE_OAUTH_CLIENT_ID', default='')
GOOGLE_DRIVE_OAUTH_CLIENT_SECRET = config('GOOGLE_DRIVE_OAUTH_CLIENT_SECRET', default='')
GOOGLE_DRIVE_OAUTH_REFRESH_TOKEN = config('GOOGLE_DRIVE_OAUTH_REFRESH_TOKEN', default='')
GOOGLE_DRIVE_OAUTH_TOKEN_URI = config('GOOGLE_DRIVE_OAUTH_TOKEN_URI', default='https://oauth2.googleapis.com/token')
GOOGLE_DRIVE_SERVICE_ACCOUNT_FILE = config('GOOGLE_DRIVE_SERVICE_ACCOUNT_FILE', default='')
GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON = config('GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON', default='')
GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON_BASE64 = config('GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON_BASE64', default='')
GOOGLE_DRIVE_PROOF_FOLDER_ID = config('GOOGLE_DRIVE_PROOF_FOLDER_ID', default='')
GOOGLE_DRIVE_PUBLIC_LINK = config('GOOGLE_DRIVE_PUBLIC_LINK', default=True, cast=bool)


# Custom user model (optional - using default)
AUTH_USER_MODEL = 'auth.User'
# Login/Logout URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='LeadSync <noreply@leadsync.com>')
SUPPORT_PHONE = config('SUPPORT_PHONE', default='')
SUPPORT_WHATSAPP = config('SUPPORT_WHATSAPP', default='')

# Stripe Configuration
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

# Google Analytics (GA4)
GA_MEASUREMENT_ID = config('GA_MEASUREMENT_ID', default='G-SPX23FVZZN')

# Renewal workflow (manual payment + auto-renew reminders)
RENEWAL_NOTICE_DAYS = config('RENEWAL_NOTICE_DAYS', default=7, cast=int)
RENEWAL_GRACE_DAYS = config('RENEWAL_GRACE_DAYS', default=3, cast=int)
RENEWAL_REMINDER_DAYS = config('RENEWAL_REMINDER_DAYS', default='7,3,1,0')
SITE_BASE_URL = config('SITE_BASE_URL', default='')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Caching — LocMem is fine for single-server. For multi-server, switch to Redis/Memcached.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # Default cache timeout: 5 minutes
    }
}

# Session configuration — use cached sessions for faster reads
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'

# Database health checks (Django 5.1+)
CONN_HEALTH_CHECKS = True

# CORS Configuration for React Frontend
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:5173,http://localhost:3000').split(',')
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}
