from django.urls import path
from django.shortcuts import redirect
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('dashboard/chart-data/', views.dashboard_chart_data, name='dashboard_chart_data'),
    path('dashboard/chart-export/', views.dashboard_chart_export, name='dashboard_chart_export'),
    path('dashboard/team-data/', views.dashboard_team_data, name='dashboard_team_data'),
    path('dashboard/team-export/', views.export_team_report, name='export_team_report'),
    path('dashboard/team-stacked-data/', views.dashboard_team_stacked_data, name='dashboard_team_stacked_data'),
    path('dashboard/team-stacked-export/', views.dashboard_team_stacked_export, name='dashboard_team_stacked_export'),
    path('add/', views.add_lead, name='add_lead'),
    path('bulk-add/', views.bulk_add_leads, name='bulk_add_leads'),
    path('edit/<int:lead_id>/', views.edit_lead, name='edit_lead'),
    path('detail/<int:lead_id>/', views.lead_detail, name='lead_detail'),
    path('delete/<int:lead_id>/', views.delete_lead, name='delete_lead'),
    path('lead/<int:lead_id>/update-status/', views.update_lead_status, name='update_lead_status'),
    path('list/', views.lead_list, name='lead_list'),
    path('categories/', views.manage_categories, name='manage_categories'),
    path('categories/edit/<int:category_id>/', views.edit_category, name='edit_category'),
    path('categories/delete/<int:category_id>/', views.delete_category, name='delete_category'),
    path('sources/', views.manage_sources, name='manage_sources'),
    path('sources/edit/<int:source_id>/', views.edit_source, name='edit_source'),
    path('sources/delete/<int:source_id>/', views.delete_source, name='delete_source'),
    path('templates/', views.manage_templates, name='manage_templates'),
    path('templates/edit/<int:template_id>/', views.edit_template, name='edit_template'),
    path('templates/delete/<int:template_id>/', views.delete_template, name='delete_template'),
    path('templates/apply/<int:template_id>/', views.apply_template, name='apply_template'),
    path('csv-upload/', views.csv_upload, name='csv_upload'),
    path('download-sample-csv/', views.download_sample_csv, name='download_sample_csv'),
    path('export-leads-csv/', views.export_leads_csv, name='export_leads_csv'),
    path('activity-log/', views.activity_log, name='activity_log'),
    path('deleted-leads/', views.deleted_leads, name='deleted_leads'),
    path('lead/<int:lead_id>/assign/', views.lead_assignment, name='lead_assignment'),
    path('analytics/', views.lead_analytics, name='lead_analytics'),
    path('analytics/monthly-chart-data/', views.analytics_monthly_chart_data, name='analytics_monthly_chart_data'),
    path('analytics/monthly-chart-export/', views.analytics_monthly_chart_export, name='analytics_monthly_chart_export'),
    path('employee-analytics/', lambda request: redirect('lead_analytics'), name='employee_analytics'),
    path('custom-fields/', views.custom_fields, name='custom_fields'),
    path('custom-fields/edit/<int:field_id>/', views.edit_custom_field, name='edit_custom_field'),
    path('custom-fields/delete/<int:field_id>/', views.delete_custom_field, name='delete_custom_field'),
    path('search/', views.search_leads, name='search_leads'),
    path('chat/', views.chat_screen, name='chat_screen'),
    path('chat/<int:user_id>/', views.chat_screen, name='chat_with_user'),
    path('chat/group/<int:group_id>/', views.chat_screen, name='chat_with_group'),
    path('chat/<int:user_id>/updates/', views.chat_thread_updates, name='chat_thread_updates'),
    path('chat/group/<int:group_id>/updates/', views.chat_group_updates, name='chat_group_updates'),
    path('chat/typing-status/', views.chat_typing_status, name='chat_typing_status'),
    path('chat/send-message/', views.chat_send_message, name='chat_send_message'),
    path('chat/send-group-message/', views.chat_send_group_message, name='chat_send_group_message'),

    # Notification URLs
    path('notifications/', views.all_notifications, name='all_notifications'),
    path('notifications/read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('notifications/clear-all/', views.clear_all_notifications, name='clear_all_notifications'),
    path('notifications/api/', views.api_notifications, name='api_notifications'),
    path('chat/unread-count/', views.api_chat_unread_count, name='api_chat_unread_count'),
]