# Generated by Django 5.2.11 on 2026-02-10 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role name e.g. Manager, HR, Senior', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of this role')),
                ('can_view_leads', models.BooleanField(default=True, verbose_name='View Leads')),
                ('can_add_leads', models.BooleanField(default=False, verbose_name='Add Leads')),
                ('can_edit_leads', models.BooleanField(default=False, verbose_name='Edit Leads')),
                ('can_delete_leads', models.BooleanField(default=False, verbose_name='Delete Leads')),
                ('can_bulk_add_leads', models.BooleanField(default=False, verbose_name='Bulk Add Leads')),
                ('can_csv_upload', models.BooleanField(default=False, verbose_name='CSV Upload')),
                ('can_manage_templates', models.BooleanField(default=False, verbose_name='Manage Templates')),
                ('can_manage_custom_fields', models.BooleanField(default=False, verbose_name='Manage Custom Fields')),
                ('can_view_analytics', models.BooleanField(default=False, verbose_name='View Analytics')),
                ('can_view_activity_log', models.BooleanField(default=False, verbose_name='View Activity Log')),
                ('can_view_deleted_leads', models.BooleanField(default=False, verbose_name='View Deleted Leads')),
                ('can_assign_leads', models.BooleanField(default=False, verbose_name='Assign Leads')),
                ('can_share_leads', models.BooleanField(default=False, verbose_name='Share Leads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='team.role'),
        ),
    ]
