# Generated by Django 5.2.10 on 2026-01-23 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_lead_facebook_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='profilelink',
            options={'ordering': ['platform', 'custom_platform']},
        ),
        migrations.AlterField(
            model_name='profilelink',
            name='custom_platform',
            field=models.CharField(blank=True, help_text='Specify platform name if not in predefined list', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profilelink',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profileplatform'),
        ),
    ]
