# Generated by Django 5.2.10 on 2026-01-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profileplatform_alter_profilelink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelink',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('website', 'Website'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='profilelink',
            options={'ordering': ['platform']},
        ),
        migrations.AlterField(
            model_name='profilelink',
            name='custom_platform',
            field=models.CharField(blank=True, help_text="Specify platform name if 'Other' selected", max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProfilePlatform',
        ),
    ]
