# Generated by Django 5.2.10 on 2026-01-27 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customfield_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('import', 'Import'), ('export', 'Export'), ('login', 'Login'), ('logout', 'Logout')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='target_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID of the object being acted upon', null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='target_model',
            field=models.CharField(db_index=True, help_text='Model name being acted upon', max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='target_name',
            field=models.CharField(blank=True, db_index=True, help_text='Name/description of the target object', max_length=200),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Estimated budget of the lead', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='client_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='converted_to_customer',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='decision_maker',
            field=models.BooleanField(db_index=True, default=False, help_text='Is the contact the decision maker?'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='follow_up_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_score',
            field=models.IntegerField(db_index=True, default=0, help_text='Score based on lead quality criteria'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='timeline',
            field=models.DateField(blank=True, db_index=True, help_text='Expected timeline for decision', null=True),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'timestamp'], name='core_activi_user_id_81b1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', 'timestamp'], name='core_activi_action_549521_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['target_model', 'target_id'], name='core_activi_target__e6bf9a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp'], name='core_activi_timesta_44c73d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner', 'status'], name='core_lead_owner_i_f9b3bc_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_by', 'created_at'], name='core_lead_created_ca0f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['follow_up_date', 'status'], name='core_lead_follow__156bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['converted_to_customer', 'created_at'], name='core_lead_convert_2a8acd_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner', 'created_at'], name='core_lead_owner_i_e6218b_idx'),
        ),
    ]
