# Generated by Django 5.2.10 on 2026-02-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_activitylog_core_activi_user_id_81b1f1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='requirement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
