# Generated by Django 5.2.13 on 2026-04-25 10:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_group_message_receipts(apps, schema_editor):
    ChatGroupMessage = apps.get_model('core', 'ChatGroupMessage')
    ChatGroupMember = apps.get_model('core', 'ChatGroupMember')
    ChatGroupMessageReceipt = apps.get_model('core', 'ChatGroupMessageReceipt')

    memberships_by_group = {}
    for membership in ChatGroupMember.objects.all().only('group_id', 'user_id'):
        memberships_by_group.setdefault(membership.group_id, []).append(membership.user_id)

    receipt_rows = []
    now = django.utils.timezone.now()
    for message in ChatGroupMessage.objects.all().only('id', 'group_id', 'sender_id'):
        for recipient_id in memberships_by_group.get(message.group_id, []):
            if recipient_id == message.sender_id:
                continue
            receipt_rows.append(
                ChatGroupMessageReceipt(
                    message_id=message.id,
                    recipient_id=recipient_id,
                    delivered_at=now,
                )
            )

    if receipt_rows:
        ChatGroupMessageReceipt.objects.bulk_create(receipt_rows, ignore_conflicts=True, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_ownercategory_ownersource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroupMessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.chatgroupmessage')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_message_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['message', 'recipient'], name='core_chatgr_message_907b8b_idx'), models.Index(fields=['recipient', 'seen_at'], name='core_chatgr_recipie_04fa0a_idx'), models.Index(fields=['recipient', 'delivered_at'], name='core_chatgr_recipie_7db985_idx')],
                'unique_together': {('message', 'recipient')},
            },
        ),
        migrations.CreateModel(
            name='ChatPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['last_seen_at'], name='core_chatpr_last_se_760f39_idx')],
            },
        ),
        migrations.RunPython(backfill_group_message_receipts, migrations.RunPython.noop),
    ]
