# Generated by Django 5.2.9 on 2026-04-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_lead_status_alter_leadtemplate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('not_contacted', 'Not Contacted'), ('contacted', 'Contacted'), ('no_response', 'No Response'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadtemplate',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('not_contacted', 'Not Contacted'), ('contacted', 'Contacted'), ('no_response', 'No Response'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
